package com.example.currencyconverter1.util

import com.example.currencyconverter1.R

// ✅ Master flag map (countries + fallback)
val flagMap = mapOf(
        "US" to R.drawable.flag_us_compressed,
        "PK" to R.drawable.flag_pk_compressed,
        "IN" to R.drawable.flag_in_compressed,
        "SA" to R.drawable.flag_sa_compressed,
        "EU" to R.drawable.flag_ec_compressed,
        "GB" to R.drawable.flag_gb_compressed,
        "JP" to R.drawable.flag_jp_compressed,
        "CN" to R.drawable.flag_cn_compressed,
        "AE" to R.drawable.flag_ga_compressed,
        "AF" to R.drawable.flag_so_compressed,
        "AO" to R.drawable.flag_ua_compressed,
        "AR" to R.drawable.flag_st_compressed,
        "AT" to R.drawable.flag_tf_compressed,
        "AU" to R.drawable.flag_ug_compressed,
        "AZ" to R.drawable.flag_tz_compressed,
        "BD" to R.drawable.flag_tf_compressed,
        "BE" to R.drawable.flag_no_compressed,
        "BH" to R.drawable.flag_gb_compressed,
        "BO" to R.drawable.flag_vu_compressed,
        "BR" to R.drawable.flag_nf_compressed,
        "CA" to R.drawable.flag_ec_compressed,
        "NZ" to R.drawable.flag_nz_compressed,
        "CH" to R.drawable.flag_ch_compressed,
        "SG" to R.drawable.flag_sg_compressed,
        "HK" to R.drawable.flag_hk_compressed,
        "KR" to R.drawable.flag_kr_compressed,
        "TH" to R.drawable.flag_th_compressed,
        "MY" to R.drawable.flag_my_compressed,
        "ID" to R.drawable.flag_id_compressed,
        "PH" to R.drawable.flag_ph_compressed,
        "VN" to R.drawable.flag_vn_compressed,
        "LK" to R.drawable.flag_lk_compressed,
        "IR" to R.drawable.flag_ir_compressed,
        "IQ" to R.drawable.flag_iq_compressed,
        "TR" to R.drawable.flag_tr_compressed,
        "RU" to R.drawable.flag_ru_compressed,
        "UA" to R.drawable.flag_ua_compressed,
        "KZ" to R.drawable.flag_kz_compressed,
        "UZ" to R.drawable.flag_uz_compressed,
        "GE" to R.drawable.flag_ge_compressed,
        "ZA" to R.drawable.flag_za_compressed,
        "NG" to R.drawable.flag_ng_compressed,
        "EG" to R.drawable.flag_eg_compressed,
        "KE" to R.drawable.flag_ke_compressed,
        "TZ" to R.drawable.flag_tz_compressed,
        "ET" to R.drawable.flag_et_compressed,
        "GH" to R.drawable.flag_gh_compressed,
        "MX" to R.drawable.flag_mx_compressed,
        "CL" to R.drawable.flag_cl_compressed,
        "CO" to R.drawable.flag_co_compressed,
        "VE" to R.drawable.flag_ve_compressed,
        "PE" to R.drawable.flag_pe_compressed,
        "UY" to R.drawable.flag_uy_compressed,
        "CZ" to R.drawable.flag_cz_compressed,
        "SE" to R.drawable.flag_se_compressed,
        "NO" to R.drawable.flag_no_compressed,
        "DK" to R.drawable.flag_dk_compressed,
        "FI" to R.drawable.flag_fi_compressed,
        "PL" to R.drawable.flag_pl_compressed,
        "HU" to R.drawable.flag_hu_compressed,
        "RO" to R.drawable.flag_ro_compressed,
        "SK" to R.drawable.flag_sk_compressed,
        "HR" to R.drawable.flag_hr_compressed,
        "GR" to R.drawable.flag_gr_compressed,
        "PT" to R.drawable.flag_pt_compressed,
        "ES" to R.drawable.flag_es_compressed,
        "IT" to R.drawable.flag_it_compressed,
        "DE" to R.drawable.flag_de_compressed,
        "FR" to R.drawable.flag_fr_compressed,
        "NL" to R.drawable.flag_nl_compressed,
        "IE" to R.drawable.flag_ie_compressed,
        "IS" to R.drawable.flag_is_compressed,
        "LU" to R.drawable.flag_lu_compressed,
        "LI" to R.drawable.flag_li_compressed,
        "MT" to R.drawable.flag_mt_compressed,
        "CY" to R.drawable.flag_cy_compressed,
        "IL" to R.drawable.flag_il_compressed,
        "QA" to R.drawable.flag_qa_compressed,
        "KW" to R.drawable.flag_kw_compressed,
        "OM" to R.drawable.flag_om_compressed,
        "JO" to R.drawable.flag_jo_compressed,
        "LB" to R.drawable.flag_lb_compressed,
        "YE" to R.drawable.flag_ye_compressed,
        "SD" to R.drawable.flag_sd_compressed,
        "DZ" to R.drawable.flag_dz_compressed,
        "MA" to R.drawable.flag_ma_compressed,
        "TN" to R.drawable.flag_tn_compressed,
        "LY" to R.drawable.flag_ly_compressed,
        "SN" to R.drawable.flag_sn_compressed,
        "CM" to R.drawable.flag_cm_compressed,
        "ZW" to R.drawable.flag_zw_compressed,
        "UG" to R.drawable.flag_ug_compressed,
        "ZM" to R.drawable.flag_zm_compressed,
        "NA" to R.drawable.flag_na_compressed,
        "MZ" to R.drawable.flag_mz_compressed,
        "RW" to R.drawable.flag_rw_compressed,
        "MW" to R.drawable.flag_mw_compressed,
        "BF" to R.drawable.bf_flag,
        "BJ" to R.drawable.bj_flag,
        "ML" to R.drawable.flag_ml_compressed,
        "NE" to R.drawable.flag_ne_compressed,
        "TG" to R.drawable.flag_tg_compressed,
        "CI" to R.drawable.flag_ci_compressed,
        "CF" to R.drawable.cf_flag,
        "GA" to R.drawable.flag_ga_compressed,
        "VN" to R.drawable.flag_vn_compressed,
        "LOGO" to R.drawable.flag_logo_compressed
)

// ✅ Currency → Country flag conversion
private val currencyToCountry = mapOf(
        "USD" to "US", "PKR" to "PK", "INR" to "IN", "AED" to "AE", "SAR" to "SA",
        "EUR" to "EU", "GBP" to "GB", "JPY" to "JP", "CNY" to "CN", "CAD" to "CA",
        "AUD" to "AU", "NZD" to "NZ", "CHF" to "CH", "SGD" to "SG", "HKD" to "HK",
        "KRW" to "KR", "THB" to "TH", "MYR" to "MY", "IDR" to "ID", "BDT" to "BD",
        "PHP" to "PH", "VND" to "VN", "LKR" to "LK", "AFN" to "AF", "IRR" to "IR",
        "IQD" to "IQ", "TRY" to "TR", "RUB" to "RU", "UAH" to "UA", "KZT" to "KZ",
        "UZS" to "UZ", "AZN" to "AZ", "GEL" to "GE", "ZAR" to "ZA", "NGN" to "NG",
        "EGP" to "EG", "KES" to "KE", "TZS" to "TZ", "ETB" to "ET", "GHS" to "GH",
        "BRL" to "BR", "MXN" to "MX", "ARS" to "AR", "CLP" to "CL", "COP" to "CO",
        "PEN" to "PE", "VEF" to "VE", "CZK" to "CZ", "SEK" to "SE", "NOK" to "NO",
        "DKK" to "DK", "PLN" to "PL", "HUF" to "HU", "RON" to "RO", "SKK" to "SK",
        "HRK" to "HR", "GRD" to "GR", "ESP" to "ES", "ITL" to "IT", "DEM" to "DE",
        "FRF" to "FR", "NLG" to "NL", "BEF" to "BE", "ATS" to "AT", "IEP" to "IE",
        "ILS" to "IL", "QAR" to "QA", "KWD" to "KW", "OMR" to "OM", "BHD" to "BH",
        "JOD" to "JO", "LBP" to "LB", "YER" to "YE", "DZD" to "DZ", "MAD" to "MA",
        "TND" to "TN", "LYD" to "LY", "AOA" to "AO", "MZN" to "MZ", "RWF" to "RW",
        "MWK" to "MW", "UGX" to "UG", "ZMW" to "ZM", "NAD" to "NA", "BIF" to "BF",
        "GMD" to "GM", "SLL" to "SL", "SDG" to "SD", "SOS" to "SO", "SSP" to "SS",
        "DJF" to "DJ", "GNF" to "GN", "PGK" to "PG", "LAK" to "LA", "KHR" to "KH"
)

// ✅ Safe function to get correct flag from currency code
fun getFlagResId(currencyCode: String?): Int {
        val upperCode = currencyCode?.uppercase() ?: return flagMap["LOGO"]!!
        val countryCode = currencyToCountry[upperCode] ?: upperCode.take(2)
        return flagMap[countryCode] ?: flagMap["LOGO"]!!
}
